version: "3.7"

services:
# Define an node-red service
  node-red:
    image: nodered/node-red:latest
    container_name: tracker-node-red
    environment:
      - TZ=Australia/Sydney
    ports:
      - "1880:1880"
    networks:
      - backend
    volumes:
      - node-red_data:/data
  # Define an InfluxDB service
  influxdb:
    image: "influxdb:${INFLUXDB_VERSION}"
    container_name: tracker-influxdb
    restart: unless-stopped
    networks:
      - backend    
    volumes:
      - influxdb_data:/var/lib/influxdb
    ports:
      - "8086:8086"   
  # Define a Chronograf service
  chronograf:
    image: "chronograf:${CRONOGRAF_VERSION}"
    container_name: tracker-chronograf
    restart: unless-stopped
    networks:
      - backend
      - frontend
    environment:
      INFLUXDB_URL: http://influxdb:8086
    ports:
      - "8888:8888"
    links:
      - influxdb
  # Define a service using Grafana
  grafana:
    image: "grafana/grafana:${GRAFANA_VERSION}"
    container_name: tracker-grafana
    restart: unless-stopped
    networks:
      - backend
      - frontend
    ports:
      - "3000:3000"
    volumes:
      # - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./config/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml:ro
      - grafana_data:/var/lib/grafana 

networks:
  backend:
  frontend:

volumes:
  grafana_data:
  node-red_data:
  influxdb_data:
